In [13]:
import pandas as pd
import json
df = json.load(open('./node_modules/tourism_viewpoint_node.json'))
tourism_viewpoint=pd.DataFrame(df['elements'])
tourism_viewpoint

,type,id,lat,lon,tags
0,node,30815438,52.569974,13.294091,"{'amenity': 'shelter', 'shelter_type': 'Wetter..."
1,node,132595900,52.404046,13.124991,"{'direction': '45', 'tourism': 'viewpoint'}"
2,node,132764590,52.403144,13.093248,"{'name': 'Victoriahöhe', 'tourism': 'viewpoint'}"
3,node,156850034,52.497718,13.242954,"{'ele': '120', 'name': 'Teufelsberg', 'natural..."
4,node,247461326,52.404389,13.033444,{'tourism': 'viewpoint'}
...,...,...,...,...,...
254,node,8931299152,52.487989,13.275393,{'tourism': 'viewpoint'}
255,node,9024702237,52.506772,13.334563,{'tourism': 'viewpoint'}
256,node,9026936271,52.401704,13.366960,"{'name': 'Alpengipfel', 'tourism': 'viewpoint'}"
257,node,9038673666,52.482133,13.291911,"{'direction': 'E', 'tourism': 'viewpoint'}"
258,node,9180246277,52.363764,13.533663,{'description': 'Plane spotting östlich der Sü...